name: Ryan McKnight
description: Tech and design
markdown: kramdown 
exclude: ["scss", "Gemfile","Gemfile.lock", "README.md","config.rb"]
disqus_short_name: "Ryan McKnight"
url: https://mcknightlabs.com
