name: rtmup
description: Notes on self-mastery and leadership
markdown: kramdown 
exclude: ["scss", "Gemfile","Gemfile.lock", "README.md","config.rb"]
disqus_short_name: "rtmup"
url: http://rtmup.com
